### ISSUE TITLE
Update Social Sharing Image for Repo

### ISSUE THREAD

**Issue by splatyourbugs** [bobbyg603/myQtCrasher#17]
Follow these instructions for this repo to add social sharing image - [https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview)

Social image for github. 
![bugsplat-github-social-sharable](https://user-images.githubusercontent.com/20464226/149037672-91778c68-1dec-48e0-9353-92b96245e89f.png)

**Comment by bobbyg603** [comment]
Done!
