### ISSUE TITLE
Cannot use Debug Info for crashpad libraries

### ISSUE THREAD

**Issue by aholster** [bobbyg603/myQtCrasher#28]
Hello, you might recognize me from discord!
I'm trying to port this example to be built with meson and clang instead, and i've encountered a problem, when using the supplied prebuilt crashpad libraries for a debug build it gives multiple warnings to the effect of:

`lld-link: warning: Cannot use debug info for 'common.lib(common.crash_report_database_win.obj)' [LNK4099]
>>> failed to load reference 'C:\www\src\3rdParty\crashpad\crashpad\out\Default\obj\client\common_cc.pdb': no such file or directory`

when i run symbols.bat on the resulting executable, it also gives the the following warning:
`..\Crashpad\Tools\Windows\symbols.bat : Warning: Could not get file version for .\myQtCrasher.exe`

the release build has no linker warnings, but does error when symbols.bat is run:
`..\Crashpad\Tools\Windows\symbols.bat : loadDataForExe failed for .\myQtCrasher.exe
At line:1 char:1
+ ..\Crashpad\Tools\Windows\symbols.bat . fred myQtCrasher 1.0 > ..\Cra ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (loadDataForExe ...myQtCrasher.exe:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Could not get symbol data from .\myQtCrasher.exe`

All this is on a windows native build, and i have managed a fully functional build using locally built crashpad

**Comment by bobbyg603** [comment]
We updated symupload and I don't think this is an issue anymore.
