### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by ignus2** [bobbyg603/myQtCrasher#30]
I got no crash dumps generated on Windows (nothing in the folders where they should be), using Qt 6.3.0 and MSVC 2019.
I compiled crashpad manually and tried a simple test program which worked, so after some investigation I nailed it down to the following:
If StartHandler() is called in synchronous init mode (NOT async) before a QWidget is shown, then it seems the connection to crashpad_handler.exe gets lost somehow (or something), therefore no dumps get generated on a crash.

```
int main(int argc, char *argv[])
{
	InitCrashpad()..., StartHandler(), etc.
	Application a(argc, argv);
	MainWindow w;
	*(volatile int*)0 = 0; // <-- dump works if crash is here
	w.show();
	*(volatile int*)0 = 0; // <-- no dump if crash is here, or any time later
	return a.exec();
}
```

However, if StartHandler() is called AFTER the first QWidget.show() call, then it works afterwards.
It also starts to work if I manually call `client->SetHandlerIPCPipe(client->GetHandlerIPCPipe())` AFTER the first QWidget.show() call.

So apparently, the first QWidget.show() call does something which makes an already initialized crashpad stop working.

Subsequent QWidget.show() calls don't affect the behaviour, just the very first one.

This issue is unrelated to BugSplat, so I'm not sure if this is the right place to report, but still worth investigating.

This might be related to #27

**Comment by bobbyg603** [comment]
hi @ignus2 👋, thanks for reporting this issue. i'm not entirely sure what to do about this problem. we don't maintain Qt or have much insight as to how the internals work, ditto with Crashpad. perhaps a note in the README or comment in the source about this issue might be sufficient to prevent people from getting into this situation?

**Comment by ignus2** [comment]
Could you reproduce it BTW? If so, then I consider the bug confirmed and maybe raise an issue with crashpad and/or Qt.
For the time being, keep this issue open (if it's confirmed and if that's OK).

**Comment by bobbyg603** [comment]
I was never able to reproduce this.
