### ISSUE TITLE
not compiled with qt5.14.2 and msvc 2017

### ISSUE THREAD

**Issue by lzq420241** [bobbyg603/myQtCrasher#36]
it complains  E:\code\my-qt-crasher\Crashpad\Include\crashpad\third_party\mini_chromium\mini_chromium\base\files\file_path.h:195: error: C2429: property "nodiscard"  need compiler flag "/std:c++17"

**Comment by bobbyg603** [comment]
Apologies, the Crashpad libraries are generated and build from a machine that uses with MSVC 2019, you'll need to either generate your own Crashpad libraries on a machine with MSVC 2017, or build the Qt project with MSVC 2019.
