### ISSUE TITLE
link error on Qt 5.15.2(win) and Qt 6.4.3(win) building with msvc2019 

### ISSUE THREAD

**Issue by copewang** [bobbyg603/myQtCrasher#37]
common.lib(common.crash_report_database_win.obj) : error LNK2019: unresolved external symbol __std_init_once_link_alternate_names_and_abort referenced in function "void __cdecl std::call_once<class <lambda_99b440d29ead4813ced356e45e33ae86> >(struct std::once_flag &,class <lambda_99b440d29ead4813ced356e45e33ae86> &&)" (??$call_once@V<lambda_99b440d29ead4813ced356e45e33ae86>@@$$V@std@@YAXAEAUonce_flag@0@$$QEAV<lambda_99b440d29ead4813ced356e45e33ae86>@@@Z)

client.lib(client.crashpad_client_win.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "void * * __cdecl __std_find_trivial<void *,void *>(void * *,void * *,void * const)" (??$__std_find_trivial@PEAXPEAX@@YAPEAPEAXPEAPEAX0QEAX@Z)

debug\myQtCrasher.exe : fatal error LNK1120: 2 unresolved externals

**Comment by bobbyg603** [comment]
hi @copewang, although we've done our best to be compatible in all environments, your best bet is to follow our [guide](https://docs.bugsplat.com/introduction/getting-started/integrations/cross-platform/crashpad/how-to-build-google-crashpad) to build crashpad yourself to ensure compatibility in your environment.
