### ISSUE TITLE
Build Crashpad into shared library for dynamic link

### ISSUE THREAD

**Issue by jiannanya** [bobbyg603/myQtCrasher#38]
Hi, I want to know is there a guide about how to build Crashpad into shared library for dynamic link?  
Maybe both for MacOS and Windows.
Thanks in advance.

**Comment by bobbyg603** [comment]
Hi there 👋,

This section of our docs contains a link that describes how to build a shared library on Windows. I don't know the args you'd have to add on macOS but I'd imagine this is how you'd do it.

https://docs.bugsplat.com/introduction/getting-started/integrations/cross-platform/qt#building-crashpad

Good luck!
