### ISSUE TITLE
Architecture compatibility

### ISSUE THREAD

**Issue by jiannanya** [bobbyg603/myQtCrasher#39]
Hi there.

If I use arm64 cpu , and the app is built with x64 target along with the x64 version crashpad, the app runs well but crashpad does not output any dump file after the app crashed.

But if I use arm64 cpu, build app and use crashpad with same arch, everything goes well.

So my question is, must I use same arch about crashpad with cpu, like arm64 cpu with arm64 version crashpad,or x64 cpu with x64 version crashpad, for catching any crash normally？

The architecture of cpu and crashpad architecture must identical？

**Comment by bobbyg603** [comment]
@jiannanya as far as I know there is no way to build Crashpad for universal (but I could be wrong!) so you'll want to use the Intel/Arm libraries accordingly matching the build target architecture
